openapi: 3.0.0
info:
  title: Greet API
  version: 1.0.0
paths:
  /greet:
    get:
      summary: Greet endpoint
      parameters:
        - name: name
          in: query
          description: The name to greet
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      tags:
        - Greetings